board:
  trace:
    - clock:
        device_pin: 'O_DAC_SCLK'
        part_pin: 'SCLK'
        delay:
            max: 2.0
            min: 1.0
    - data_out:
        device_pin: 'O_DAC_DATA'
        part_pin: 'SDIN'
        delay:
            max: 2.5
            min: 1.5
    - data_in:
        device_pin: 'I_DAC_DATA'
        part_pin: 'SDO'
        delay:
            max: 1.5
            min: 0.5
    - chip_select:
        device_pin: 'O_DAC_CSF'
        part_pin: 'SYNC_F'
        delay:
            max: 1.5
            min: 0.5
    - data_bus:
        device_pin: 'O_DAC_DATA_BUS[4]'
        part_pin: 'INPUT_DATA_BUS'
        delay:
            max: 1.5
            min: 0.5
device:
    vendor: 'Intel'
    name: 'Arria10'
    interface:
        - DAC_DATA:
            clock:
               internal:
                   - clock_100mhz_int:
                        frequency: '100 MHz'
               output:
                   - O_DAC_SCLK:
                        frequency: '20 MHz'
            data:
                input:
                    - I_DAC_DATA:
                        launch_clock:
                            name: 'O_DAC_SCLK'
                            edge: 3
                        capture_clock:
                            name: 'clock_100mhz_int'
                            edge:
                                setup: 'q'
                                hold: 'c'
                output:
                    - O_DAC_DATA:
                        launch_clock:
                            name: 'clock_100mhz_int'
                            edge: 6
                        capture_clock:
                            name: 'O_DAC_SCLK'
                            edge:
                                setup: 'c'
                                hold: 'a'
                    - O_DAC_CSF:
                        launch_clock:
                            name: 'clock_100mhz_int'
                            edge: 8
                        capture_clock:
                            name: 'O_DAC_SCLK'
                            edge:
                                setup: 'd'
                                hold: 'b'
                    - O_DAC_DATA_BUS[4]:
                        launch_clock:
                            name: 'clock_100mhz_int'
                            edge: 14
                        capture_clock:
                            name: 'O_DAC_SCLK'
                            edge:
                                setup: 'e'
                                hold: 'b'
                    
part:
    vendor: 'Texas Instruments'
    name: 'DAC81404'
    interface:
        - serial_data:
            timing_model: 'source_synchronous_with_round_trip'
            clock:
                input:
                    - SCLK:
                        max_freq: '50 MHz'
            data:
                input:
                    - SDIN:
                        clock: 'SCLK'
                        falling:
                            setup:
                                id: 'tSDIS'
                                value: 5.0
                            hold:
                                id: 'tSDIH'
                                value: 5.0
                    - SYNC_F:
                        clock: 'SCLK'
                        falling:
                            setup:
                                id: 'tCSS'
                                value: 20.0
                            hold:
                                id: 'tCSH'
                                value: 5.0
                    - INPUT_DATA_BUS:
                        clock: 'SCLK'
                        rising:
                            setup:
                                id: 'tDebugSetup'
                                value: 20.0
                            hold:
                                id: 'tDebugHold'
                                value: 5.0
                output:
                    - SDO:
                        clock: 'SCLK'
                        rising:
                            clock_to_out_max:
                               id: 'tSDODLY'
                               value: 20.0
                            clock_to_out_min:
                               id: 'tSDODLY'
                               value: 0
